# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'XMToolOC' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for XMToolOC
	pod 'AFNetworking'




  target 'XMToolOCTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'XMToolOCUITests' do
    # Pods for testing
  end

end
